version: "3.3"

services:
  redis:
    image: redis
  web:
    build: .
    command: sh -c "python3 -m uvicorn main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - redis
